### ISSUE TITLE
ImportError: No module named builtuins when importing java.lang.Exception

### ISSUE THREAD

**Issue by thecesrom** [thecesrom/Ignition#47]
Steps to reproduce:

1. Run `python2`
2. `from java.lang import Exception as JException`

```bash
$ python2
Python 2.7.18 (default, Nov  9 2020, 16:23:15) 
[GCC Apple LLVM 12.0.0 (clang-1200.0.32.21)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from java.lang import Exception as JException
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/thecesrom/.pyenv/versions/ignition-api-27/lib/python2.7/site-packages/java/lang/__init__.py", line 23, in <module>
    from builtins import Exception as PyException
ImportError: No module named builtins
```

**Comment by thecesrom** [comment]
Introduced in commit 29d87d1
