### ISSUE TITLE
AttributeError: 'module' object has no attribute '_copy_dispatch'

### ISSUE THREAD

**Issue by thecesrom** [thecesrom/Ignition#53]
Commit ea530ac on [`main`](https://github.com/thecesrom/Ignition/tree/main), c94b517 on [`7.9`](https://github.com/thecesrom/Ignition/tree/7.9), and 0992a8c on [`8.0`](https://github.com/thecesrom/Ignition/tree/8.0) introduced an unintended bug.

When updating `ignition-api` via `pip` I got the following error:

```bash
$ python -m pip install --upgrade ignition-api
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
Collecting ignition-api
  Downloading ignition_api-8.1.13-py2-none-any.whl (127 kB)
     |████████████████████████████████| 127 kB 2.3 MB/s 
Requirement already satisfied, skipping upgrade: typing in ./.pyenv/versions/2.7.18/envs/incendium/lib/python2.7/site-packages (from ignition-api) (3.10.0.0)
Installing collected packages: ignition-api
  Attempting uninstall: ignition-api
    Found existing installation: ignition-api 8.1.12.post3
    Uninstalling ignition-api-8.1.12.post3:
      Successfully uninstalled ignition-api-8.1.12.post3
Successfully installed ignition-api-8.1.13
Traceback (most recent call last):
  File "/Users/thecesrom/.pyenv/versions/2.7.18/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/thecesrom/.pyenv/versions/2.7.18/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/thecesrom/.pyenv/versions/2.7.18/envs/incendium/lib/python2.7/site-packages/pip/__main__.py", line 23, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/Users/thecesrom/.pyenv/versions/incendium/lib/python2.7/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/Users/thecesrom/.pyenv/versions/incendium/lib/python2.7/site-packages/pip/_internal/cli/autocompletion.py", line 4, in <module>
    import optparse
  File "/Users/thecesrom/.pyenv/versions/2.7.18/lib/python2.7/optparse.py", line 90, in <module>
    from gettext import gettext
  File "/Users/thecesrom/.pyenv/versions/2.7.18/lib/python2.7/gettext.py", line 49, in <module>
    import locale, copy, os, re, struct, sys
  File "/Users/thecesrom/.pyenv/versions/2.7.18/lib/python2.7/copy.py", line 60, in <module>
    from org.python.core import PyStringMap
  File "/Users/thecesrom/.pyenv/versions/incendium/lib/python2.7/site-packages/org/python/core/__init__.py", line 5, in <module>
    from java.lang import Object
  File "/Users/thecesrom/.pyenv/versions/incendium/lib/python2.7/site-packages/java/lang/__init__.py", line 22, in <module>
    from typing import Union
  File "/Users/thecesrom/.pyenv/versions/incendium/lib/python2.7/site-packages/typing.py", line 1440, in <module>
    copy._copy_dispatch[GenericMeta] = _copy_generic
AttributeError: 'module' object has no attribute '_copy_dispatch'
Traceback (most recent call last):
  File "/Users/thecesrom/.pyenv/versions/2.7.18/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/thecesrom/.pyenv/versions/2.7.18/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/thecesrom/.pyenv/versions/2.7.18/envs/incendium/lib/python2.7/site-packages/pip/__main__.py", line 23, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "/Users/thecesrom/.pyenv/versions/incendium/lib/python2.7/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/Users/thecesrom/.pyenv/versions/incendium/lib/python2.7/site-packages/pip/_internal/cli/autocompletion.py", line 4, in <module>
    import optparse
  File "/Users/thecesrom/.pyenv/versions/2.7.18/lib/python2.7/optparse.py", line 90, in <module>
    from gettext import gettext
  File "/Users/thecesrom/.pyenv/versions/2.7.18/lib/python2.7/gettext.py", line 49, in <module>
    import locale, copy, os, re, struct, sys
  File "/Users/thecesrom/.pyenv/versions/2.7.18/lib/python2.7/copy.py", line 60, in <module>
    from org.python.core import PyStringMap
  File "/Users/thecesrom/.pyenv/versions/incendium/lib/python2.7/site-packages/org/python/core/__init__.py", line 5, in <module>
    from java.lang import Object
  File "/Users/thecesrom/.pyenv/versions/incendium/lib/python2.7/site-packages/java/lang/__init__.py", line 22, in <module>
    from typing import Union
  File "/Users/thecesrom/.pyenv/versions/incendium/lib/python2.7/site-packages/typing.py", line 1440, in <module>
    copy._copy_dispatch[GenericMeta] = _copy_generic
AttributeError: 'module' object has no attribute '_copy_dispatch'
```

After that `pip` cannot be executed.

Rolling back the `java.lang.String` changes should solve the problem.

**Comment by thecesrom** [comment]
Closed via 75d3bb8 (`7.9`), 739c194 (`8.0`), and 8b9c99c (`main`).
